# netlify.toml

[build]
  # build from the client/ folder
  base    = "client"
  # publish the dist/ output (not client/dist)
  publish = "dist"
  # install & build
  command = "npm install && npm run build"

[build.environment]
  # pin Node to 18.x so Rollup’s optional native deps won’t break
  NODE_VERSION = "18.x"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
