# netlify.toml

[build]
  base    = "client"
  publish = "dist"
  command = "npm install && npm run build"

[build.environment]
  # Use the Node 18 major line (Netlify accepts "18")
  NODE_VERSION = "18"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
